export const FACING = {

  MAP: new Map(),

  NORTH: 'NORTH',
  EAST: 'EAST',
  WEST: 'WEST',
  SOUTH: 'SOUTH'
}

FACING.MAP.set('NORTH', FACING.NORTH)
FACING.MAP.set('EAST', FACING.EAST)
FACING.MAP.set('WEST', FACING.WEST)
FACING.MAP.set('SOUTH', FACING.SOUTH)

export const COMMAND = {
  MAP: new Map(),
  PLACE: 'PLACE',
  MOVE: 'MOVE',
  REPORT: 'REPORT'
}

export const ROTATE = {
  RIGHT: 'RIGHT',
  LEFT: 'LEFT'
}

COMMAND.MAP.set('PLACE', COMMAND.PLACE)
COMMAND.MAP.set('MOVE', COMMAND.MOVE)
COMMAND.MAP.set('REPORT', COMMAND.REPORT)
COMMAND.MAP.set('LEFT', ROTATE.LEFT)
COMMAND.MAP.set('RIGHT', ROTATE.RIGHT)
